import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ShotSpec } from "./types";
import { discoverRoutes } from "./route-discovery";
import { SHOTS } from "./manifest";

export type CoverageStatus =
  | "covered"
  | "missing"
  | "needs-seed"
  | "stale"
  | "skipped";

export type CoverageRow = {
  route: string;
  status: CoverageStatus;
  module?: string;
  slug?: string;
  reason?: string;
};

/** Diff the manifest against the real route list. Pure. */
export function computeCoverage(
  routes: string[],
  shots: ShotSpec[],
  skipped: Record<string, string> = {},
): CoverageRow[] {
  const shotByPath = new Map(shots.map((s) => [s.path, s]));
  const rows: CoverageRow[] = [];

  for (const route of routes) {
    const shot = shotByPath.get(route);
    if (!shot) {
      rows.push({ route, status: "missing" });
    } else if (route.includes(":") && !shot.seedId) {
      rows.push({ route, status: "needs-seed", module: shot.module, slug: shot.slug });
    } else if (skipped[route]) {
      rows.push({
        route,
        status: "skipped",
        module: shot.module,
        slug: shot.slug,
        reason: skipped[route],
      });
    } else {
      rows.push({ route, status: "covered", module: shot.module, slug: shot.slug });
    }
  }

  const real = new Set(routes);
  for (const shot of shots) {
    if (!real.has(shot.path)) {
      rows.push({ route: shot.path, status: "stale", module: shot.module, slug: shot.slug });
    }
  }
  return rows;
}

/** Render the coverage rows as a Markdown report. Pure. */
export function renderReport(rows: CoverageRow[]): string {
  const counts: Record<string, number> = {};
  for (const r of rows) counts[r.status] = (counts[r.status] ?? 0) + 1;
  const summary = (["covered", "missing", "needs-seed", "skipped", "stale"] as const)
    .map((s) => `${s}: ${counts[s] ?? 0}`)
    .join(" | ");

  const header = [
    "# Screenshot Coverage",
    "",
    "_Auto-generated by `bun run wiki:coverage` in carmen-inventory-frontend-e2e._",
    "",
    `**Total routes: ${rows.length}** — ${summary}`,
    "",
    "| Route | Status | Module | Slug | Note |",
    "|-------|--------|--------|------|------|",
  ];
  const body = rows
    .sort((a, b) => a.route.localeCompare(b.route))
    .map(
      (r) =>
        `| \`${r.route}\` | ${r.status} | ${r.module ?? ""} | ${r.slug ?? ""} | ${r.reason ?? ""} |`,
    );
  return [...header, ...body, ""].join("\n");
}

/** CLI entry: discover routes, diff against SHOTS, write the report into the wiki. */
function main(): void {
  const frontendDir = process.env.E2E_FRONTEND_DIR ?? "../carmen-inventory-frontend";
  const specsDir = process.env.WIKI_SPECS_DIR ?? "../carmen-wiki/.specs";
  const resultsPath = join(process.cwd(), "tests/wiki-screenshots/last-run.json");

  const routes = discoverRoutes(join(frontendDir, "app"));
  const skipped: Record<string, string> = existsSync(resultsPath)
    ? JSON.parse(readFileSync(resultsPath, "utf8"))
    : {};
  const md = renderReport(computeCoverage(routes, SHOTS, skipped));

  const out = join(specsDir, "screenshot-coverage.md");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, md);
  console.log(`Wrote ${out} (${routes.length} routes)`);
}

// @ts-ignore – import.meta.main is a Bun-specific CLI guard; tsc uses commonjs module mode
if (import.meta.main) main();
