import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ShotSpec } from "./types";
import { discoverFrontendRoutes } from "./route-discovery";
import { SHOTS } from "./manifest";
import { loadSeedOverlay, applySeedOverlay } from "./seed-overlay";
import { loadRoleMatrix, ROLE_MATRIX_PATH, baselineFor, rolesToCapture } from "./role-matrix";

export type CoverageStatus =
  | "covered"
  | "missing"
  | "needs-seed"
  | "stale"
  | "skipped";

export type CoverageRow = {
  route: string;
  status: CoverageStatus;
  module?: string;
  slug?: string;
  reason?: string;
};

/** Diff the manifest against the real route list. Pure. */
export function computeCoverage(
  routes: string[],
  shots: ShotSpec[],
  skipped: Record<string, string> = {},
): CoverageRow[] {
  const shotByPath = new Map(shots.map((s) => [s.path, s]));
  const rows: CoverageRow[] = [];

  for (const route of routes) {
    const shot = shotByPath.get(route);
    if (shot && route.includes(":") && !shot.seedId) {
      rows.push({ route, status: "needs-seed", module: shot.module, slug: shot.slug });
    } else if (skipped[route]) {
      rows.push({
        route,
        status: "skipped",
        module: shot?.module,
        slug: shot?.slug,
        reason: skipped[route],
      });
    } else if (!shot) {
      rows.push({ route, status: "missing" });
    } else {
      rows.push({ route, status: "covered", module: shot.module, slug: shot.slug });
    }
  }

  const real = new Set(routes);
  for (const shot of shots) {
    if (!real.has(shot.path)) {
      rows.push({ route: shot.path, status: "stale", module: shot.module, slug: shot.slug });
    }
  }
  return rows;
}

/** Render the coverage rows as a Markdown report. Pure. */
export function renderReport(
  rows: CoverageRow[],
  rolesByRoute: Record<string, string> = {},
): string {
  const counts: Record<string, number> = {};
  for (const r of rows) counts[r.status] = (counts[r.status] ?? 0) + 1;
  const summary = (["covered", "missing", "needs-seed", "skipped", "stale"] as const)
    .map((s) => `${s}: ${counts[s] ?? 0}`)
    .join(" | ");

  const header = [
    "# Screenshot Coverage",
    "",
    "_Auto-generated by `bun run wiki:coverage` in carmen-inventory-frontend-e2e._",
    "",
    `**Routes: ${rows.filter((r) => r.status !== "stale").length}** (manifest-only/stale: ${rows.filter((r) => r.status === "stale").length}) — ${summary}`,
    "",
    "| Route | Status | Module | Slug | Roles | Note |",
    "|-------|--------|--------|------|-------|------|",
  ];
  const body = rows
    .sort((a, b) => a.route.localeCompare(b.route))
    .map(
      (r) =>
        `| \`${r.route}\` | ${r.status} | ${r.module ?? ""} | ${r.slug ?? ""} | ${rolesByRoute[r.route] ?? ""} | ${r.reason ?? ""} |`,
    );
  return [...header, ...body, ""].join("\n");
}

/** CLI entry: discover routes, diff against SHOTS, write the report into the wiki. */
function main(): void {
  const frontendDir =
    process.env.E2E_FRONTEND_DIR ?? "../carmen-inventory-frontend-react";
  const specsDir = process.env.WIKI_SPECS_DIR ?? "../carmen-wiki/.specs";
  const resultsPath = join(process.cwd(), "tests/wiki-screenshots/last-run.json");
  const seedIdsPath = join(process.cwd(), "tests/wiki-screenshots/seed-ids.json");

  const routes = discoverFrontendRoutes(frontendDir);
  let skipped: Record<string, string> = {};
  if (existsSync(resultsPath)) {
    try {
      skipped = JSON.parse(readFileSync(resultsPath, "utf8"));
    } catch {
      console.warn(`Ignoring malformed ${resultsPath}`);
    }
  }
  // Discovered seedIds (gitignored, env-specific) count toward coverage just
  // like hand-set ones, so a route auto-seeded this run isn't reported needs-seed.
  const shots = applySeedOverlay(SHOTS, loadSeedOverlay(seedIdsPath));

  // The role matrix is optional here: coverage still works before the first
  // probe run, it just cannot show the Roles column.
  const rolesByRoute: Record<string, string> = {};
  try {
    const matrix = loadRoleMatrix(ROLE_MATRIX_PATH);
    for (const route of new Set(matrix.map((r) => r.route))) {
      const base = baselineFor(matrix, route);
      if (!base) {
        rolesByRoute[route] = "none";
        continue;
      }
      const extra = rolesToCapture(matrix, route);
      rolesByRoute[route] = extra.length ? `${base.role} +${extra.length}` : base.role;
    }
  } catch {
    console.warn("No role-matrix.json yet — Roles column will be empty. Run: bun run wiki:probe");
  }
  const md = renderReport(computeCoverage(routes, shots, skipped), rolesByRoute);

  const out = join(specsDir, "screenshot-coverage.md");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, md);
  console.log(`Wrote ${out} (${routes.length} routes)`);
}

// @ts-expect-error import.meta.main is a Bun-specific CLI guard; tsc uses commonjs module mode
if (import.meta.main) main();
