// AUTO-GENERATED by `bun run wiki:seed`, then hand-curated.
// Re-running the seed OVERWRITES this file — curate via PR, not regeneration.
import type { ShotSpec } from "./types";

export const SHOTS: ShotSpec[] = [
  { path: "/config", module: "config", slug: "index", wikiTarget: "master-data/index" },
  { path: "/config/adjustment-type", module: "adjustment-type", slug: "index", wikiTarget: "master-data/adjustment-type" },
  { path: "/config/business-type", module: "business-type", slug: "index", wikiTarget: ["master-data/business-unit", "master-data/vendor-business-type"] },
  { path: "/vendor-management/certification", module: "certification", slug: "index" },
  { path: "/config/credit-note-reason", module: "credit-note-reason", slug: "index", wikiTarget: "master-data/credit-note-reason" },
  { path: "/config/credit-term", module: "credit-term", slug: "index", wikiTarget: "master-data/credit-term" },
  { path: "/config/currency", module: "currency", slug: "index", wikiTarget: "master-data/currency" },
  { path: "/config/delivery-point", module: "delivery-point", slug: "index", wikiTarget: "master-data/delivery-point" },
  { path: "/config/department", module: "department", slug: "index", wikiTarget: "master-data/department" },
  // TODO: set seedId
  { path: "/config/department/:id", module: "department", slug: "detail", wikiTarget: ["master-data/department-detail", "access-control/department-user"] },
  { path: "/config/department/new", module: "department", slug: "new" },
  { path: "/product-management/eco", module: "eco", slug: "index" },
  { path: "/config/exchange-rate", module: "exchange-rate", slug: "index", wikiTarget: "master-data/exchange-rate" },
  { path: "/config/extra-cost", module: "extra-cost", slug: "index", wikiTarget: "master-data/extra-cost-type" },
  { path: "/config/location", module: "location", slug: "index", wikiTarget: "master-data/location" },
  // TODO: set seedId
  { path: "/config/location/:id", module: "location", slug: "detail", wikiTarget: ["master-data/location-detail", "access-control/user-location"] },
  { path: "/config/location/new", module: "location", slug: "new" },
  { path: "/config/tax-profile", module: "tax-profile", slug: "index", wikiTarget: "master-data/tax-profile" },
  { path: "/config/unit", module: "unit", slug: "index", wikiTarget: "master-data/unit" },
  { path: "/dashboard", module: "dashboard", slug: "index", wikiTarget: ["dashboard/main", "dashboard/widget-workspace", "dashboard/my-pending"] },
  { path: "/inventory-management", module: "inventory-management", slug: "index", wikiTarget: "inventory/index" },
  { path: "/inventory-management/inventory-adjustment", module: "inventory-adjustment", slug: "index", wikiTarget: "inventory-adjustment/index" },
  // TODO: set seedId
  { path: "/inventory-management/inventory-adjustment/:id", module: "inventory-adjustment", slug: "detail" },
  { path: "/inventory-management/inventory-adjustment/new", module: "inventory-adjustment", slug: "new" },
  { path: "/inventory-management/period-end", module: "period-end", slug: "index", wikiTarget: "inventory/period-end" },
  { path: "/inventory-management/period-end/review", module: "period-end", slug: "review" },
  { path: "/inventory-management/physical-count", module: "physical-count", slug: "index", wikiTarget: "physical-count/index" },
  // TODO: set seedId
  { path: "/inventory-management/physical-count/:id", module: "physical-count", slug: "detail", wikiTarget: "physical-count/detail" },
  // TODO: set seedId
  { path: "/inventory-management/physical-count/:id/entry", module: "physical-count", slug: "entry" },
  // TODO: set seedId
  { path: "/inventory-management/physical-count/:id/review", module: "physical-count", slug: "review" },
  { path: "/inventory-management/physical-count/new", module: "physical-count", slug: "new" },
  { path: "/inventory-management/spot-check", module: "spot-check", slug: "index", wikiTarget: "spot-check/index" },
  // TODO: set seedId
  { path: "/inventory-management/spot-check/:id", module: "spot-check", slug: "detail" },
  // TODO: set seedId
  { path: "/inventory-management/spot-check/:id/review", module: "spot-check", slug: "review" },
  // TODO: set seedId — NOTE: collides with /config/location/:id (both -> location/detail.png); give this a distinct module/slug before seeding
  { path: "/inventory-management/spot-check/location/:location_id", module: "location", slug: "detail" },
  { path: "/inventory-management/transaction", module: "transaction", slug: "index", wikiTarget: "inventory/transaction" },
  { path: "/notifications", module: "notifications", slug: "index", wikiTarget: "reporting-audit/notification" },
  { path: "/operation-plan", module: "operation-plan", slug: "index" },
  { path: "/operation-plan/category", module: "category", slug: "index", wikiTarget: "recipe/category" },
  // TODO: set seedId
  { path: "/operation-plan/category/:id", module: "category", slug: "detail" },
  { path: "/operation-plan/category/new", module: "category", slug: "new" },
  { path: "/operation-plan/cuisine", module: "cuisine", slug: "index", wikiTarget: "recipe/cuisine" },
  // TODO: set seedId
  { path: "/operation-plan/cuisine/:id", module: "cuisine", slug: "detail" },
  { path: "/operation-plan/cuisine/new", module: "cuisine", slug: "new" },
  { path: "/operation-plan/equipment", module: "equipment", slug: "index", wikiTarget: "recipe/equipment" },
  { path: "/operation-plan/equipment-category", module: "equipment-category", slug: "index", wikiTarget: "recipe/equipment-category" },
  // TODO: set seedId
  { path: "/operation-plan/equipment/:id", module: "equipment", slug: "detail" },
  { path: "/operation-plan/equipment/new", module: "equipment", slug: "new" },
  { path: "/operation-plan/recipe", module: "recipe", slug: "index", wikiTarget: "recipe/index" },
  { path: "/operation-plan/recipe-equipment-category", module: "recipe-equipment-category", slug: "index" },
  // TODO: set seedId
  { path: "/operation-plan/recipe/:id", module: "recipe", slug: "detail", wikiTarget: "recipe/detail" },
  { path: "/operation-plan/recipe/new", module: "recipe", slug: "new" },
  { path: "/procurement", module: "procurement", slug: "index" },
  { path: "/procurement/approval", module: "approval", slug: "index", wikiTarget: ["purchase-request/my-approval", "dashboard/my-approval"] },
  { path: "/procurement/credit-note", module: "credit-note", slug: "index", wikiTarget: "purchase-order/credit-note" },
  // TODO: set seedId
  { path: "/procurement/credit-note/:id", module: "credit-note", slug: "detail", wikiTarget: "purchase-order/credit-note-detail" },
  { path: "/procurement/credit-note/new", module: "credit-note", slug: "new" },
  { path: "/procurement/goods-receive-note", module: "goods-receive-note", slug: "index", wikiTarget: "good-receive-note/index" },
  // TODO: set seedId
  { path: "/procurement/goods-receive-note/:id", module: "goods-receive-note", slug: "detail", wikiTarget: "good-receive-note/detail" },
  { path: "/procurement/goods-receive-note/new", module: "goods-receive-note", slug: "new" },
  { path: "/procurement/purchase-order", module: "purchase-order", slug: "index", wikiTarget: "purchase-order/index" },
  // TODO: set seedId
  { path: "/procurement/purchase-order/:id", module: "purchase-order", slug: "detail", wikiTarget: "purchase-order/detail" },
  { path: "/procurement/purchase-order/from-price-list", module: "from-price-list", slug: "index" },
  { path: "/procurement/purchase-order/new", module: "purchase-order", slug: "new" },
  { path: "/procurement/purchase-request", module: "purchase-request", slug: "index", wikiTarget: "purchase-request/index" },
  { path: "/procurement/purchase-request-template", module: "purchase-request-template", slug: "index", wikiTarget: "templates/purchase-request" },
  // TODO: set seedId
  { path: "/procurement/purchase-request-template/:id", module: "purchase-request-template", slug: "detail", wikiTarget: "templates/purchase-request-detail" },
  { path: "/procurement/purchase-request-template/new", module: "purchase-request-template", slug: "new" },
  // TODO: set seedId
  { path: "/procurement/purchase-request/:id", module: "purchase-request", slug: "detail", wikiTarget: "purchase-request/detail" },
  { path: "/procurement/purchase-request/new", module: "purchase-request", slug: "new" },
  { path: "/product-management", module: "product-management", slug: "index" },
  { path: "/product-management/category", module: "category", slug: "index", wikiTarget: "product/category" },
  { path: "/product-management/product", module: "product", slug: "index", wikiTarget: "product/index" },
  // TODO: set seedId
  { path: "/product-management/product/:id", module: "product", slug: "detail", wikiTarget: "product/detail" },
  { path: "/product-management/product/new", module: "product", slug: "new" },
  { path: "/profile", module: "profile", slug: "index" },
  { path: "/profile/setting", module: "setting", slug: "index" },
  { path: "/report", module: "report", slug: "index", wikiTarget: "reporting-audit/report" },
  { path: "/report/history", module: "history", slug: "index", wikiTarget: "reporting-audit/history" },
  { path: "/report/list", module: "list", slug: "index" },
  { path: "/report/schedules", module: "schedules", slug: "index", wikiTarget: "reporting-audit/schedule" },
  { path: "/store-operation", module: "store-operation", slug: "index" },
  { path: "/store-operation/stock-replenishment", module: "stock-replenishment", slug: "index", wikiTarget: "store-requisition/stock-replenishment" },
  { path: "/store-operation/store-requisition", module: "store-requisition", slug: "index", wikiTarget: "store-requisition/index" },
  // TODO: set seedId
  { path: "/store-operation/store-requisition/:id", module: "store-requisition", slug: "detail", wikiTarget: "store-requisition/detail" },
  { path: "/store-operation/store-requisition/new", module: "store-requisition", slug: "new" },
  { path: "/store-operation/wastage-reporting", module: "wastage-reporting", slug: "index", wikiTarget: "inventory-adjustment/wastage-reporting" },
  // TODO: set seedId
  { path: "/store-operation/wastage-reporting/:id", module: "wastage-reporting", slug: "detail" },
  { path: "/store-operation/wastage-reporting/new", module: "wastage-reporting", slug: "new" },
  { path: "/system-admin", module: "system-admin", slug: "index", wikiTarget: "system-config/index" },
  { path: "/system-admin/activity-log", module: "activity-log", slug: "index", wikiTarget: "reporting-audit/activity" },
  { path: "/system-admin/config-email", module: "config-email", slug: "index" },
  { path: "/system-admin/dashboard-dataset", module: "dashboard-dataset", slug: "index", wikiTarget: ["system-config/dashboard-dataset", "reporting-audit/widget"] },
  { path: "/system-admin/document", module: "document", slug: "index", wikiTarget: ["system-config/document", "reporting-audit/attachment"] },
  { path: "/system-admin/notification-template", module: "notification-template", slug: "index" },
  // TODO: set seedId
  { path: "/system-admin/notification-template/:id", module: "notification-template", slug: "detail" },
  { path: "/system-admin/notification-template/new", module: "notification-template", slug: "new" },
  { path: "/system-admin/inventory-period", module: "inventory-period", slug: "index", wikiTarget: "system-config/period" },
  { path: "/system-admin/query-dataset", module: "query-dataset", slug: "index" },
  { path: "/system-admin/role", module: "role", slug: "index", wikiTarget: "access-control/application-role" },
  // TODO: set seedId
  { path: "/system-admin/role/:id", module: "role", slug: "detail", wikiTarget: ["access-control/application-role-detail", "access-control/permission"] },
  { path: "/system-admin/role/new", module: "role", slug: "new" },
  { path: "/system-admin/running-code", module: "running-code", slug: "index", wikiTarget: "system-config/running-code" },
  { path: "/system-admin/user", module: "user", slug: "index", wikiTarget: "access-control/user" },
  { path: "/system-admin/user-activity", module: "user-activity", slug: "index", wikiTarget: "reporting-audit/user-activity" },
  // TODO: set seedId
  { path: "/system-admin/user/:id", module: "user", slug: "detail", wikiTarget: ["access-control/user-detail", "access-control/business-unit-user"] },
  { path: "/system-admin/workflow", module: "workflow", slug: "index", wikiTarget: "system-config/workflow" },
  // TODO: set seedId
  { path: "/system-admin/workflow/:id", module: "workflow", slug: "detail", wikiTarget: "system-config/workflow-detail" },
  { path: "/system-admin/workflow/new", module: "workflow", slug: "new" },
  { path: "/vendor-management", module: "vendor-management", slug: "index" },
  { path: "/vendor-management/price-list", module: "price-list", slug: "index", wikiTarget: "vendor-pricelist/index" },
  { path: "/vendor-management/price-list-template", module: "price-list-template", slug: "index", wikiTarget: "templates/price-list" },
  // TODO: set seedId
  { path: "/vendor-management/price-list-template/:id", module: "price-list-template", slug: "detail", wikiTarget: "templates/price-list-detail" },
  { path: "/vendor-management/price-list-template/new", module: "price-list-template", slug: "new" },
  // TODO: set seedId
  { path: "/vendor-management/price-list/:id", module: "price-list", slug: "detail" },
  { path: "/vendor-management/price-list/new", module: "price-list", slug: "new" },
  { path: "/vendor-management/request-price-list", module: "request-price-list", slug: "index", wikiTarget: "vendor-pricelist/request-price-list" },
  // TODO: set seedId
  { path: "/vendor-management/request-price-list/:id", module: "request-price-list", slug: "detail", wikiTarget: "vendor-pricelist/request-price-list-detail" },
  { path: "/vendor-management/request-price-list/new", module: "request-price-list", slug: "new" },
  { path: "/vendor-management/vendor", module: "vendor", slug: "index", wikiTarget: "master-data/vendor" },
  // TODO: set seedId
  { path: "/vendor-management/vendor/:id", module: "vendor", slug: "detail", wikiTarget: "master-data/vendor-detail" },
  { path: "/vendor-management/vendor/new", module: "vendor", slug: "new" },
  // Dialog-based config modules: the create form has no route of its own, so
  // capture it by opening the list page's Add dialog.
  { path: "/config/adjustment-type", module: "adjustment-type", slug: "index", interaction: "add-dialog" },
  { path: "/config/business-type", module: "business-type", slug: "index", interaction: "add-dialog" },
  { path: "/vendor-management/certification", module: "certification", slug: "index", interaction: "add-dialog" },
  { path: "/config/credit-note-reason", module: "credit-note-reason", slug: "index", interaction: "add-dialog" },
  { path: "/config/credit-term", module: "credit-term", slug: "index", interaction: "add-dialog" },
  { path: "/config/currency", module: "currency", slug: "index", interaction: "add-dialog" },
  { path: "/config/delivery-point", module: "delivery-point", slug: "index", interaction: "add-dialog" },
  { path: "/product-management/eco", module: "eco", slug: "index", interaction: "add-dialog" },
  { path: "/config/exchange-rate", module: "exchange-rate", slug: "index", interaction: "add-dialog" },
  { path: "/config/extra-cost", module: "extra-cost", slug: "index", interaction: "add-dialog" },
  { path: "/config/tax-profile", module: "tax-profile", slug: "index", interaction: "add-dialog" },
  { path: "/config/unit", module: "unit", slug: "index", interaction: "add-dialog" },
  // Added for the 2026-09-23 wiki screenshot sync (wikiTarget-only shots).
  { path: "/config/chart-of-accounts", module: "chart-of-accounts", slug: "index", wikiTarget: "master-data/chart-of-accounts" },
  { path: "/config/shelf", module: "shelf", slug: "index", wikiTarget: "master-data/shelf" },
  { path: "/system-admin/email-profile", module: "email-profile", slug: "index", wikiTarget: "system-config/config-email" },
  { path: "/system-admin/company-profile", module: "company-profile", slug: "index", wikiTarget: "system-config/company-profile" },
  // "/system-admin/interface" (system-config/application-config) is not shot: on dev it renders
  // "Could not load interface settings" (rejected on visual review, 2026-09-23).
  { path: "/accounting/journal-voucher", module: "journal-voucher", slug: "index", wikiTarget: "general-ledger/index" },
];
