// AUTO-GENERATED by `bun run wiki:seed`, then hand-curated.
// Re-running the seed OVERWRITES this file — curate via PR, not regeneration.
import type { ShotSpec } from "./types";

export const SHOTS: ShotSpec[] = [
  { path: "/config", module: "config", slug: "index" },
  { path: "/config/adjustment-type", module: "adjustment-type", slug: "index" },
  { path: "/config/business-type", module: "business-type", slug: "index" },
  { path: "/config/certification", module: "certification", slug: "index" },
  { path: "/config/credit-note-reason", module: "credit-note-reason", slug: "index" },
  { path: "/config/credit-term", module: "credit-term", slug: "index" },
  { path: "/config/currency", module: "currency", slug: "index" },
  { path: "/config/delivery-point", module: "delivery-point", slug: "index" },
  { path: "/config/department", module: "department", slug: "index" },
  // TODO: set seedId
  { path: "/config/department/:id", module: "department", slug: "detail" },
  { path: "/config/department/new", module: "department", slug: "new" },
  { path: "/config/eco", module: "eco", slug: "index" },
  { path: "/config/exchange-rate", module: "exchange-rate", slug: "index" },
  { path: "/config/extra-cost", module: "extra-cost", slug: "index" },
  { path: "/config/location", module: "location", slug: "index" },
  // TODO: set seedId
  { path: "/config/location/:id", module: "location", slug: "detail" },
  { path: "/config/location/new", module: "location", slug: "new" },
  { path: "/config/tax-profile", module: "tax-profile", slug: "index" },
  { path: "/config/unit", module: "unit", slug: "index" },
  { path: "/dashboard", module: "dashboard", slug: "index" },
  { path: "/inventory-management", module: "inventory-management", slug: "index" },
  { path: "/inventory-management/inventory-adjustment", module: "inventory-adjustment", slug: "index" },
  // TODO: set seedId
  { path: "/inventory-management/inventory-adjustment/:id", module: "inventory-adjustment", slug: "detail" },
  { path: "/inventory-management/inventory-adjustment/new", module: "inventory-adjustment", slug: "new" },
  { path: "/inventory-management/period-end", module: "period-end", slug: "index" },
  { path: "/inventory-management/period-end/review", module: "period-end", slug: "review" },
  { path: "/inventory-management/physical-count", module: "physical-count", slug: "index" },
  // TODO: set seedId
  { path: "/inventory-management/physical-count/:id", module: "physical-count", slug: "detail" },
  // TODO: set seedId
  { path: "/inventory-management/physical-count/:id/entry", module: "physical-count", slug: "entry" },
  // TODO: set seedId
  { path: "/inventory-management/physical-count/:id/review", module: "physical-count", slug: "review" },
  { path: "/inventory-management/physical-count/new", module: "physical-count", slug: "new" },
  { path: "/inventory-management/spot-check", module: "spot-check", slug: "index" },
  // TODO: set seedId
  { path: "/inventory-management/spot-check/:id", module: "spot-check", slug: "detail" },
  // TODO: set seedId
  { path: "/inventory-management/spot-check/:id/review", module: "spot-check", slug: "review" },
  // TODO: set seedId — NOTE: collides with /config/location/:id (both -> location/detail.png); give this a distinct module/slug before seeding
  { path: "/inventory-management/spot-check/location/:location_id", module: "location", slug: "detail" },
  { path: "/inventory-management/transaction", module: "transaction", slug: "index" },
  { path: "/notifications", module: "notifications", slug: "index" },
  { path: "/operation-plan", module: "operation-plan", slug: "index" },
  { path: "/operation-plan/category", module: "category", slug: "index" },
  // TODO: set seedId
  { path: "/operation-plan/category/:id", module: "category", slug: "detail" },
  { path: "/operation-plan/category/new", module: "category", slug: "new" },
  { path: "/operation-plan/cuisine", module: "cuisine", slug: "index" },
  // TODO: set seedId
  { path: "/operation-plan/cuisine/:id", module: "cuisine", slug: "detail" },
  { path: "/operation-plan/cuisine/new", module: "cuisine", slug: "new" },
  { path: "/operation-plan/equipment", module: "equipment", slug: "index" },
  { path: "/operation-plan/equipment-category", module: "equipment-category", slug: "index" },
  // TODO: set seedId
  { path: "/operation-plan/equipment/:id", module: "equipment", slug: "detail" },
  { path: "/operation-plan/equipment/new", module: "equipment", slug: "new" },
  { path: "/operation-plan/recipe", module: "recipe", slug: "index" },
  { path: "/operation-plan/recipe-equipment-category", module: "recipe-equipment-category", slug: "index" },
  // TODO: set seedId
  { path: "/operation-plan/recipe/:id", module: "recipe", slug: "detail" },
  { path: "/operation-plan/recipe/new", module: "recipe", slug: "new" },
  { path: "/procurement", module: "procurement", slug: "index" },
  { path: "/procurement/approval", module: "approval", slug: "index" },
  { path: "/procurement/credit-note", module: "credit-note", slug: "index" },
  // TODO: set seedId
  { path: "/procurement/credit-note/:id", module: "credit-note", slug: "detail" },
  { path: "/procurement/credit-note/new", module: "credit-note", slug: "new" },
  { path: "/procurement/goods-receive-note", module: "goods-receive-note", slug: "index" },
  // TODO: set seedId
  { path: "/procurement/goods-receive-note/:id", module: "goods-receive-note", slug: "detail" },
  { path: "/procurement/goods-receive-note/new", module: "goods-receive-note", slug: "new" },
  { path: "/procurement/purchase-order", module: "purchase-order", slug: "index" },
  // TODO: set seedId
  { path: "/procurement/purchase-order/:id", module: "purchase-order", slug: "detail" },
  { path: "/procurement/purchase-order/from-price-list", module: "from-price-list", slug: "index" },
  { path: "/procurement/purchase-order/new", module: "purchase-order", slug: "new" },
  { path: "/procurement/purchase-request", module: "purchase-request", slug: "index" },
  { path: "/procurement/purchase-request-template", module: "purchase-request-template", slug: "index" },
  // TODO: set seedId
  { path: "/procurement/purchase-request-template/:id", module: "purchase-request-template", slug: "detail" },
  { path: "/procurement/purchase-request-template/new", module: "purchase-request-template", slug: "new" },
  // TODO: set seedId
  { path: "/procurement/purchase-request/:id", module: "purchase-request", slug: "detail" },
  { path: "/procurement/purchase-request/new", module: "purchase-request", slug: "new" },
  { path: "/product-management", module: "product-management", slug: "index" },
  { path: "/product-management/category", module: "category", slug: "index" },
  { path: "/product-management/product", module: "product", slug: "index" },
  // TODO: set seedId
  { path: "/product-management/product/:id", module: "product", slug: "detail" },
  { path: "/product-management/product/new", module: "product", slug: "new" },
  { path: "/profile", module: "profile", slug: "index" },
  { path: "/profile/setting", module: "setting", slug: "index" },
  { path: "/report", module: "report", slug: "index" },
  { path: "/report/history", module: "history", slug: "index" },
  { path: "/report/list", module: "list", slug: "index" },
  { path: "/report/schedules", module: "schedules", slug: "index" },
  { path: "/store-operation", module: "store-operation", slug: "index" },
  { path: "/store-operation/stock-replenishment", module: "stock-replenishment", slug: "index" },
  { path: "/store-operation/store-requisition", module: "store-requisition", slug: "index" },
  // TODO: set seedId
  { path: "/store-operation/store-requisition/:id", module: "store-requisition", slug: "detail" },
  { path: "/store-operation/store-requisition/new", module: "store-requisition", slug: "new" },
  { path: "/store-operation/wastage-reporting", module: "wastage-reporting", slug: "index" },
  // TODO: set seedId
  { path: "/store-operation/wastage-reporting/:id", module: "wastage-reporting", slug: "detail" },
  { path: "/store-operation/wastage-reporting/new", module: "wastage-reporting", slug: "new" },
  { path: "/system-admin", module: "system-admin", slug: "index" },
  { path: "/system-admin/activity-log", module: "activity-log", slug: "index" },
  { path: "/system-admin/config-email", module: "config-email", slug: "index" },
  { path: "/system-admin/dashboard-dataset", module: "dashboard-dataset", slug: "index" },
  { path: "/system-admin/document", module: "document", slug: "index" },
  { path: "/system-admin/notification-template", module: "notification-template", slug: "index" },
  // TODO: set seedId
  { path: "/system-admin/notification-template/:id", module: "notification-template", slug: "detail" },
  { path: "/system-admin/notification-template/new", module: "notification-template", slug: "new" },
  { path: "/system-admin/period", module: "period", slug: "index" },
  { path: "/system-admin/query-dataset", module: "query-dataset", slug: "index" },
  { path: "/system-admin/role", module: "role", slug: "index" },
  // TODO: set seedId
  { path: "/system-admin/role/:id", module: "role", slug: "detail" },
  { path: "/system-admin/role/new", module: "role", slug: "new" },
  { path: "/system-admin/running-code", module: "running-code", slug: "index" },
  { path: "/system-admin/user", module: "user", slug: "index" },
  { path: "/system-admin/user-activity", module: "user-activity", slug: "index" },
  // TODO: set seedId
  { path: "/system-admin/user/:id", module: "user", slug: "detail" },
  { path: "/system-admin/workflow", module: "workflow", slug: "index" },
  // TODO: set seedId
  { path: "/system-admin/workflow/:id", module: "workflow", slug: "detail" },
  { path: "/system-admin/workflow/new", module: "workflow", slug: "new" },
  { path: "/vendor-management", module: "vendor-management", slug: "index" },
  { path: "/vendor-management/price-list", module: "price-list", slug: "index" },
  { path: "/vendor-management/price-list-template", module: "price-list-template", slug: "index" },
  // TODO: set seedId
  { path: "/vendor-management/price-list-template/:id", module: "price-list-template", slug: "detail" },
  { path: "/vendor-management/price-list-template/new", module: "price-list-template", slug: "new" },
  // TODO: set seedId
  { path: "/vendor-management/price-list/:id", module: "price-list", slug: "detail" },
  { path: "/vendor-management/price-list/new", module: "price-list", slug: "new" },
  { path: "/vendor-management/request-price-list", module: "request-price-list", slug: "index" },
  // TODO: set seedId
  { path: "/vendor-management/request-price-list/:id", module: "request-price-list", slug: "detail" },
  { path: "/vendor-management/request-price-list/new", module: "request-price-list", slug: "new" },
  { path: "/vendor-management/vendor", module: "vendor", slug: "index" },
  // TODO: set seedId
  { path: "/vendor-management/vendor/:id", module: "vendor", slug: "detail" },
  { path: "/vendor-management/vendor/new", module: "vendor", slug: "new" },
];
