import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { discoverRoutes } from "./route-discovery";

const ACTION_SLUGS = new Set(["new", "review", "entry"]);

/** Routes that are dev-only, unauthenticated, or token-gated — excluded from auto-seed. */
function isExcluded(route: string): boolean {
  return (
    route.startsWith("/playground") ||
    route === "/login" ||
    route.startsWith("/pl/")
  );
}

/** Infer a wiki module folder and filename slug from a canonical route. */
export function inferModuleSlug(route: string): { module: string; slug: string } {
  if (route === "/") return { module: "root", slug: "index" };
  const segs = route.split("/").filter(Boolean);
  const last = segs[segs.length - 1];

  let slug: string;
  if (last.startsWith(":")) slug = "detail";
  else if (ACTION_SLUGS.has(last)) slug = last;
  else slug = "index";

  const statics = segs.filter((s) => !s.startsWith(":") && !ACTION_SLUGS.has(s));
  const module = statics[statics.length - 1] ?? segs[0];
  return { module, slug };
}

/** Produce the TypeScript source for manifest.ts from a route list. Pure. */
export function generateManifestSource(routes: string[]): string {
  const lines = routes
    .filter((r) => !isExcluded(r))
    .sort()
    .map((r) => {
      const { module, slug } = inferModuleSlug(r);
      const entry = `  { path: ${JSON.stringify(r)}, module: ${JSON.stringify(module)}, slug: ${JSON.stringify(slug)} },`;
      return r.includes(":") ? `  // TODO: set seedId\n${entry}` : entry;
    });
  return [
    "// AUTO-GENERATED by `bun run wiki:seed`, then hand-curated.",
    "// Re-running the seed OVERWRITES this file — curate via PR, not regeneration.",
    'import type { ShotSpec } from "./types";',
    "",
    "export const SHOTS: ShotSpec[] = [",
    ...lines,
    "];",
    "",
  ].join("\n");
}

function main(): void {
  const frontendDir = process.env.E2E_FRONTEND_DIR ?? "../carmen-inventory-frontend";
  const routes = discoverRoutes(join(frontendDir, "app"));
  const out = join(process.cwd(), "tests/wiki-screenshots/manifest.ts");
  writeFileSync(out, generateManifestSource(routes));
  console.log(`Wrote ${out} (${routes.length} routes discovered)`);
}

// @ts-expect-error import.meta.main is a Bun-specific CLI guard; tsc uses commonjs module mode
if (import.meta.main) main();
